"""
Feature extraction models for structured room analysis.

Re-exports all public types from enums, modules, and outputs submodules.
"""

from app.models.features.enums import (
    ApplianceType,
    BuildingTypology,
    ConditionStatus,
    ConstructionEra,
    CountertopMaterial,
    EnergyRating,
    FinishLevel,
    FloorAccessibility,
    FloorMaterial,
    HiddenCostRisk,
    LocationCostTier,
    OutletSwitchStyle,
    PlumbingVisibleCondition,
    PropertyPurpose,
    ScopeComplexity,
    ShowerOrBath,
    VentilationType,
    WallFinish,
    WindowFrameMaterial,
    WorkScope,
)
from app.models.features.modules import (
    BathroomFeatures,
    BathroomFixturesModule,
    BathroomMEPModule,
    BathroomSurfacesModule,
    GenericFixturesModule,
    GenericMEPModule,
    GenericRoomFeatures,
    GenericSurfacesModule,
    KitchenFeatures,
    KitchenFixturesModule,
    KitchenMEPModule,
    KitchenSurfacesModule,
    PropertyContext,
    RoomFeatures,
)
from app.models.features.outputs import (
    CompositeIndices,
    CostBreakdown,
    CostLineItem,
    CostRange,
    HiddenCostRiskResult,
    ModuleConfidence,
    PropertyCostResult,
    RoomCostResult,
    ScopeComplexityResult,
    TimeEstimate,
    UserPreferences,
    WorkScopeResult,
)

__all__ = [
    # Enums
    "ApplianceType",
    "BuildingTypology",
    "ConditionStatus",
    "ConstructionEra",
    "CountertopMaterial",
    "EnergyRating",
    "FinishLevel",
    "FloorAccessibility",
    "FloorMaterial",
    "HiddenCostRisk",
    "LocationCostTier",
    "OutletSwitchStyle",
    "PlumbingVisibleCondition",
    "PropertyPurpose",
    "ScopeComplexity",
    "ShowerOrBath",
    "VentilationType",
    "WallFinish",
    "WindowFrameMaterial",
    "WorkScope",
    # Module models
    "BathroomFeatures",
    "BathroomFixturesModule",
    "BathroomMEPModule",
    "BathroomSurfacesModule",
    "GenericFixturesModule",
    "GenericMEPModule",
    "GenericRoomFeatures",
    "GenericSurfacesModule",
    "KitchenFeatures",
    "KitchenFixturesModule",
    "KitchenMEPModule",
    "KitchenSurfacesModule",
    "PropertyContext",
    "RoomFeatures",
    # Output models
    "CompositeIndices",
    "CostBreakdown",
    "CostLineItem",
    "CostRange",
    "HiddenCostRiskResult",
    "ModuleConfidence",
    "PropertyCostResult",
    "RoomCostResult",
    "ScopeComplexityResult",
    "TimeEstimate",
    "UserPreferences",
    "WorkScopeResult",
]
