"""
Output models for the cost calculator and composite indices.

Contains:
  - CostRange: min/max range with unit
  - CostBreakdown: materials + labor cost breakdown
  - ModuleConfidence: per-module confidence scores
  - UserPreferences: diy, finish_level, budget_ceiling, purpose
  - CostResult: full cost calculation result
  - Composite index models: WorkScopeResult, TimeEstimate, HiddenCostRiskResult, etc.
"""

from pydantic import BaseModel, Field

from app.models.features.enums import (
    FinishLevel,
    HiddenCostRisk,
    PropertyPurpose,
    ScopeComplexity,
    WorkScope,
)


# ---------------------------------------------------------------------------
# Cost models
# ---------------------------------------------------------------------------


class CostRange(BaseModel):
    """A min/max cost range with unit."""

    min: float = Field(ge=0, description="Minimum cost in EUR")
    max: float = Field(ge=0, description="Maximum cost in EUR")
    unit: str = Field(description="Cost unit: m2, unit, room, linear_m")


class CostBreakdown(BaseModel):
    """Materials vs labor cost breakdown."""

    materials_min: float = Field(ge=0, default=0)
    materials_max: float = Field(ge=0, default=0)
    labor_min: float = Field(ge=0, default=0)
    labor_max: float = Field(ge=0, default=0)

    @property
    def total_min(self) -> float:
        return self.materials_min + self.labor_min

    @property
    def total_max(self) -> float:
        return self.materials_max + self.labor_max


class CostLineItem(BaseModel):
    """A single cost line item generated by the cost calculator."""

    category: str = Field(description="Cost category (e.g., flooring, walls, windows)")
    action: str = Field(description="Action taken (e.g., replace, refinish, repaint)")
    description: str = Field(description="Human-readable description in Portuguese")
    cost_min: float = Field(ge=0)
    cost_max: float = Field(ge=0)
    materials_min: float = Field(ge=0)
    materials_max: float = Field(ge=0)
    labor_min: float = Field(ge=0)
    labor_max: float = Field(ge=0)
    unit: str = Field(description="Cost unit applied")
    quantity: float = Field(ge=0, description="Quantity (area or count)")
    priority: str = Field(default="media", description="alta, media, baixa")


class ModuleConfidence(BaseModel):
    """Confidence scores per feature module."""

    surfaces: float | None = Field(default=None, ge=0, le=1)
    fixtures: float | None = Field(default=None, ge=0, le=1)
    mep: float | None = Field(default=None, ge=0, le=1)
    overall: float = Field(ge=0, le=1, description="Weighted overall confidence")


# ---------------------------------------------------------------------------
# User preferences
# ---------------------------------------------------------------------------


class UserPreferences(BaseModel):
    """User-provided preferences that affect cost calculation."""

    diy: bool = Field(default=False, description="When True, strip labor costs")
    finish_level: FinishLevel = Field(
        default=FinishLevel.STANDARD,
        description="Quality level: economico (0.7x), standard (1.0x), premium (1.5x)",
    )
    budget_ceiling: float | None = Field(
        default=None, ge=0, description="User's maximum budget (display warning if exceeded)"
    )
    property_purpose: PropertyPurpose = Field(
        default=PropertyPurpose.HABITACAO_PROPRIA,
        description="Intended use of property",
    )


# ---------------------------------------------------------------------------
# Composite indices
# ---------------------------------------------------------------------------


class WorkScopeResult(BaseModel):
    """Work scope classification per module."""

    surfaces: WorkScope = Field(default=WorkScope.NONE)
    fixtures: WorkScope = Field(default=WorkScope.NONE)
    mep: WorkScope = Field(default=WorkScope.NONE)
    overall: WorkScope = Field(default=WorkScope.NONE)


class TimeEstimate(BaseModel):
    """Estimated renovation timeline."""

    weeks_min: int = Field(ge=0, default=0)
    weeks_max: int = Field(ge=0, default=0)


class HiddenCostRiskResult(BaseModel):
    """Hidden cost risk assessment."""

    level: HiddenCostRisk = Field(default=HiddenCostRisk.UNKNOWN)
    factors: list[str] = Field(
        default_factory=list,
        description="Risk factors identified (in Portuguese)",
    )


class ScopeComplexityResult(BaseModel):
    """Overall scope complexity assessment."""

    level: ScopeComplexity = Field(default=ScopeComplexity.SIMPLE)
    room_count: int = Field(ge=0, default=0)
    modules_needing_work: int = Field(ge=0, default=0)


class CompositeIndices(BaseModel):
    """All composite indices for a property analysis."""

    work_scope: WorkScopeResult = Field(default_factory=WorkScopeResult)
    time_estimate: TimeEstimate = Field(default_factory=TimeEstimate)
    hidden_cost_risk: HiddenCostRiskResult = Field(default_factory=HiddenCostRiskResult)
    scope_complexity: ScopeComplexityResult = Field(default_factory=ScopeComplexityResult)


# ---------------------------------------------------------------------------
# Full cost result
# ---------------------------------------------------------------------------


class RoomCostResult(BaseModel):
    """Cost calculation result for a single room."""

    cost_breakdown: CostBreakdown = Field(default_factory=CostBreakdown)
    line_items: list[CostLineItem] = Field(default_factory=list)
    module_confidence: ModuleConfidence = Field(
        default_factory=lambda: ModuleConfidence(overall=0.5)
    )
    work_scope: WorkScopeResult = Field(default_factory=WorkScopeResult)


class PropertyCostResult(BaseModel):
    """Cost calculation result for the entire property."""

    total_breakdown: CostBreakdown = Field(default_factory=CostBreakdown)
    room_costs: dict[str, RoomCostResult] = Field(
        default_factory=dict,
        description="Costs per room, keyed by room_label",
    )
    composite_indices: CompositeIndices = Field(default_factory=CompositeIndices)
    user_preferences: UserPreferences = Field(default_factory=UserPreferences)
